version: "3.9"
services:
    api:
        build:
            context: api 
            dockerfile: Dockerfile
        ports:
            - 8080:8080

    frontend:
        build:
            context: frontend 
            dockerfile: Dockerfile
        ports:
            - 80:80
        links:
            - api